name: Build Project

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [21]
    name: "Java ${{ matrix.java }} build"
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "${{ matrix.java }}"
          cache: "maven"
      - name: Verify build
        run: mvn verify
  sonar:
    name: Sonar analysis
    needs: build
    if: github.event_name == 'push' && github.ref_name == 'main'
    uses: ./.github/workflows/sonar-maven.yml
    with:
      save_cache: true
    secrets: inherit
