name: Check pull

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build project
    uses: ./.github/workflows/build-project.yml
  sonar:
    runs-on: ubuntu-latest
    needs: build
    name: Prepare analysis context
    steps:
      - name: Copy event payload
        run: cat "$GITHUB_EVENT_PATH" | jq .pull_request > pull_request.json
      - name: Upload event payload
        uses: actions/upload-artifact@v4
        with:
          name: pull_request
          path: pull_request.json
