name: Check pull

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build project
    uses: ./.github/workflows/build-project.yml
  sonar:
    needs: build
    name: Prepare analysis context
    uses: ./.github/workflows/sonar-pull-prepare.yml
    with: 
      pull_request: ${{ toJSON(github.event.pull_request) }}
