name: Analyse Pull Request

on:
  pull_request_target:

permissions:
  contents: read

jobs:
  analyse:
    name: Sonar analysis
    uses: ./.github/workflows/sonar-maven.yml
    with:
      pull_request: ${{ toJSON(github.event.pull_request) }}
    secrets: inherit
