name: Prepare analysis context

on:
  workflow_call:
    inputs:
      workflow_run:
        description: Associated workflow_run event
        type: string
        required: true
    outputs:
      sonar_allowed:
        description: Whether the analysis is allowed
        value: ${{ jobs.prepare.outputs.sonar_allowed }}
      pull_request:
        description: Associated pull_request event
        value: ${{ jobs.prepare.outputs.pull_request }}
        

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: Prepare context
    outputs:
      sonar_allowed: ${{ steps.export.outputs.sonar_allowed }}
      pull_request: ${{ steps.export.outputs.pull_request }}
    steps:
      - name: Fetch pull_request
        if: fromJSON(inputs.workflow_run).event == 'pull_request'
        uses: actions/download-artifact@v4
        with:
          name: pull_request
          run-id: ${{ fromJSON(inputs.workflow_run).id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Export context values
        id: export
        shell: bash
        env:
          TRIGGER_EVENT: ${{ inputs.workflow_run }}
        run: |
          SONAR_ALLOWED=false

          if [ -f pull_request.json ]; then
            echo "pull_request=$(cat pull_request.json | jq -c .)" >> "$GITHUB_OUTPUT"

            if jq -e '.base.ref == "main" == ' pull_request.json; then
              SONAR_ALLOWED=true
            fi
          fi

          # jq test na push a head_branch
          if $(echo "$TRIGGER_EVENT" | jq -e '.event == "push" and .head_branch == "main"'); then
            SONAR_ALLOWED=true
          fi

          echo "sonar_allowed=$SONAR_ALLOWED" >> "$GITHUB_OUTPUT"
