name: Trigger Sonar analysis

on:
  workflow_run:
    workflows:
      - Build project
    types:
      - completed

permissions:
  contents: read

jobs:
  prepare:
    if: github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/sonar-prepare.yml
    name: Prepare analysis context
    with:
      workflow_run: ${{ toJSON(github.event.workflow_run) }}
  trigger:
    needs: prepare
    if: needs.prepare.outputs.sonar_allowed
    name: Trigger Sonar analysis
    uses: ./.github/workflows/sonar-maven.yml
    with:
      java_version: 21
      pull_request: ${{ needs.prepare.outputs.pull_request }}
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
